# Backend services only - API only (external database)
# Usage: docker-compose -f docker-compose.backend.yml up
#
services:
  # Go API Service
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-production}
    container_name: pocketanalyst-api
    restart: unless-stopped
    environment:
      # Database configuration (using external database)
      DATABASE_URL: "postgres://postgres:${DB_PASSWORD}@host.docker.internal:5432/pocketanalyst?sslmode=disable"
      
      # API configuration
      API_PORT: ${API_PORT:-8080}
      API_HOST: ${API_HOST:-0.0.0.0}
      
      # Alpha Vantage configuration
      ALPHA_VANTAGE_API_KEY: ${ALPHA_VANTAGE_API_KEY}
      ALPHA_VANTAGE_BASE_URL: ${ALPHA_VANTAGE_BASE_URL:-https://www.alphavantage.co/query}
      
      # CORS configuration for frontend integration
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-http://localhost:3000,http://localhost:5173,http://localhost:8081}
      
      # Application environment
      APP_ENV: ${APP_ENV:-development}
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - "${API_PORT:-8080}:8080"
    networks:
      - backend-network
    volumes:
      - ./api:/app:${VOLUME_MODE:-}
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  backend-network:
    driver: bridge
